# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Validar Compilação .NET

# Gatilhos: quando este workflow deve rodar
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  "Compilando":
    # O workflow rodará em uma máquina virtual Linux (Ubuntu)
    runs-on: ubuntu-latest

    steps:
    # 1. Clona o seu repositório para dentro da máquina virtual
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configura a versão do .NET SDK.
    #    IMPORTANTE: Altere '8.0.x' para a versão que seu projeto utiliza.
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 3. Restaura os pacotes NuGet do seu projeto
    - name: Restore dependencies
      run: dotnet restore

    # 4. Compila o projeto. O --no-restore é usado porque já restauramos no passo anterior.
    #    Se este comando falhar, todo o workflow falhará.
    - name: Build project
      run: dotnet build --configuration Release --no-restore
